version: '3'
services:

  client:
    build:
      context:  ./packages/client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: ["yarn", "start"]

  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - globalchatnetwork
    depends_on:
      - database
    command: ["yarn", "start"]

  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./packages/server/globalchatDB:/data/db
    networks:
      - globalchatnetwork

networks:
  globalchatnetwork:
    driver: bridge